import Table from "./table/Table";

export const transactions = [
  {
    id: "TXN-10001",
    date: "2026-08-01",
    name: "Salary Credit",
    type: "Income",
    category: "Salary",
    amount: 85000,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Monthly salary",
  },
  {
    id: "TXN-10002",
    date: "2026-08-01",
    name: "Starbucks",
    type: "Expense",
    category: "Food & Drinks",
    amount: 420,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Coffee",
  },
  {
    id: "TXN-10003",
    date: "2026-07-31",
    name: "Amazon",
    type: "Expense",
    category: "Shopping",
    amount: 2499,
    paymentMethod: "UPI",
    status: "Completed",
    remarks: "Wireless Mouse",
  },
  {
    id: "TXN-10004",
    date: "2026-07-30",
    name: "Electricity Bill",
    type: "Expense",
    category: "Utilities",
    amount: 1840,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "July bill",
  },
  {
    id: "TXN-10005",
    date: "2026-07-29",
    name: "Freelance Project",
    type: "Income",
    category: "Freelance",
    amount: 22000,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Landing page design",
  },
  {
    id: "TXN-10006",
    date: "2026-07-28",
    name: "Uber",
    type: "Expense",
    category: "Transport",
    amount: 315,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Airport ride",
  },
  {
    id: "TXN-10007",
    date: "2026-07-28",
    name: "Netflix",
    type: "Expense",
    category: "Subscription",
    amount: 649,
    paymentMethod: "Debit Card",
    status: "Completed",
    remarks: "Monthly subscription",
  },
  {
    id: "TXN-10008",
    date: "2026-07-27",
    name: "Dividend",
    type: "Income",
    category: "Investment",
    amount: 5400,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Quarterly dividend",
  },
  {
    id: "TXN-10009",
    date: "2026-07-26",
    name: "Apollo Pharmacy",
    type: "Expense",
    category: "Healthcare",
    amount: 980,
    paymentMethod: "UPI",
    status: "Completed",
    remarks: "Medicines",
  },
  {
    id: "TXN-10010",
    date: "2026-07-25",
    name: "Pizza Hut",
    type: "Expense",
    category: "Food & Drinks",
    amount: 1125,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Dinner",
  },
  {
    id: "TXN-10011",
    date: "2026-07-24",
    name: "Google Play",
    type: "Expense",
    category: "Digital",
    amount: 199,
    paymentMethod: "UPI",
    status: "Completed",
    remarks: "Premium app",
  },
  {
    id: "TXN-10012",
    date: "2026-07-23",
    name: "Client Payment",
    type: "Income",
    category: "Business",
    amount: 48000,
    paymentMethod: "Bank Transfer",
    status: "Pending",
    remarks: "Invoice #1024",
  },
  {
    id: "TXN-10013",
    date: "2026-07-22",
    name: "Big Bazaar",
    type: "Expense",
    category: "Groceries",
    amount: 3560,
    paymentMethod: "Debit Card",
    status: "Completed",
    remarks: "Weekly groceries",
  },
  {
    id: "TXN-10014",
    date: "2026-07-21",
    name: "Fuel Station",
    type: "Expense",
    category: "Fuel",
    amount: 2500,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Petrol",
  },
  {
    id: "TXN-10015",
    date: "2026-07-20",
    name: "Interest Credit",
    type: "Income",
    category: "Savings",
    amount: 980,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Savings interest",
  },
  {
    id: "TXN-10004",
    date: "2026-07-30",
    name: "Electricity Bill",
    type: "Expense",
    category: "Utilities",
    amount: 1840,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "July bill",
  },
  {
    id: "TXN-10005",
    date: "2026-07-29",
    name: "Freelance Project",
    type: "Income",
    category: "Freelance",
    amount: 22000,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Landing page design",
  },
  {
    id: "TXN-10006",
    date: "2026-07-28",
    name: "Uber",
    type: "Expense",
    category: "Transport",
    amount: 315,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Airport ride",
  },
  {
    id: "TXN-10007",
    date: "2026-07-28",
    name: "Netflix",
    type: "Expense",
    category: "Subscription",
    amount: 649,
    paymentMethod: "Debit Card",
    status: "Completed",
    remarks: "Monthly subscription",
  },
  {
    id: "TXN-10008",
    date: "2026-07-27",
    name: "Dividend",
    type: "Income",
    category: "Investment",
    amount: 5400,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Quarterly dividend",
  },
  {
    id: "TXN-10009",
    date: "2026-07-26",
    name: "Apollo Pharmacy",
    type: "Expense",
    category: "Healthcare",
    amount: 980,
    paymentMethod: "UPI",
    status: "Completed",
    remarks: "Medicines",
  },
  {
    id: "TXN-10010",
    date: "2026-07-25",
    name: "Pizza Hut",
    type: "Expense",
    category: "Food & Drinks",
    amount: 1125,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Dinner",
  },
  {
    id: "TXN-10011",
    date: "2026-07-24",
    name: "Google Play",
    type: "Expense",
    category: "Digital",
    amount: 199,
    paymentMethod: "UPI",
    status: "Completed",
    remarks: "Premium app",
  },
  {
    id: "TXN-10012",
    date: "2026-07-23",
    name: "Client Payment",
    type: "Income",
    category: "Business",
    amount: 48000,
    paymentMethod: "Bank Transfer",
    status: "Pending",
    remarks: "Invoice #1024",
  },
  {
    id: "TXN-10013",
    date: "2026-07-22",
    name: "Big Bazaar",
    type: "Expense",
    category: "Groceries",
    amount: 3560,
    paymentMethod: "Debit Card",
    status: "Completed",
    remarks: "Weekly groceries",
  },
  {
    id: "TXN-10014",
    date: "2026-07-21",
    name: "Fuel Station",
    type: "Expense",
    category: "Fuel",
    amount: 2500,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Petrol",
  },
  {
    id: "TXN-10015",
    date: "2026-07-20",
    name: "Interest Credit",
    type: "Income",
    category: "Savings",
    amount: 980,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Savings interest",
  },
  {
    id: "TXN-10004",
    date: "2026-07-30",
    name: "Electricity Bill",
    type: "Expense",
    category: "Utilities",
    amount: 1840,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "July bill",
  },
  {
    id: "TXN-10005",
    date: "2026-07-29",
    name: "Freelance Project",
    type: "Income",
    category: "Freelance",
    amount: 22000,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Landing page design",
  },
  {
    id: "TXN-10006",
    date: "2026-07-28",
    name: "Uber",
    type: "Expense",
    category: "Transport",
    amount: 315,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Airport ride",
  },
  {
    id: "TXN-10007",
    date: "2026-07-28",
    name: "Netflix",
    type: "Expense",
    category: "Subscription",
    amount: 649,
    paymentMethod: "Debit Card",
    status: "Completed",
    remarks: "Monthly subscription",
  },
  {
    id: "TXN-10008",
    date: "2026-07-27",
    name: "Dividend",
    type: "Income",
    category: "Investment",
    amount: 5400,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Quarterly dividend",
  },
  {
    id: "TXN-10009",
    date: "2026-07-26",
    name: "Apollo Pharmacy",
    type: "Expense",
    category: "Healthcare",
    amount: 980,
    paymentMethod: "UPI",
    status: "Completed",
    remarks: "Medicines",
  },
  {
    id: "TXN-10010",
    date: "2026-07-25",
    name: "Pizza Hut",
    type: "Expense",
    category: "Food & Drinks",
    amount: 1125,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Dinner",
  },
  {
    id: "TXN-10011",
    date: "2026-07-24",
    name: "Google Play",
    type: "Expense",
    category: "Digital",
    amount: 199,
    paymentMethod: "UPI",
    status: "Completed",
    remarks: "Premium app",
  },
  {
    id: "TXN-10012",
    date: "2026-07-23",
    name: "Client Payment",
    type: "Income",
    category: "Business",
    amount: 48000,
    paymentMethod: "Bank Transfer",
    status: "Pending",
    remarks: "Invoice #1024",
  },
  {
    id: "TXN-10013",
    date: "2026-07-22",
    name: "Big Bazaar",
    type: "Expense",
    category: "Groceries",
    amount: 3560,
    paymentMethod: "Debit Card",
    status: "Completed",
    remarks: "Weekly groceries",
  },
  {
    id: "TXN-10014",
    date: "2026-07-21",
    name: "Fuel Station",
    type: "Expense",
    category: "Fuel",
    amount: 2500,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Petrol",
  },
  {
    id: "TXN-10015",
    date: "2026-07-20",
    name: "Interest Credit",
    type: "Income",
    category: "Savings",
    amount: 980,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Savings interest",
  },
  {
    id: "TXN-10004",
    date: "2026-07-30",
    name: "Electricity Bill",
    type: "Expense",
    category: "Utilities",
    amount: 1840,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "July bill",
  },
  {
    id: "TXN-10005",
    date: "2026-07-29",
    name: "Freelance Project",
    type: "Income",
    category: "Freelance",
    amount: 22000,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Landing page design",
  },
  {
    id: "TXN-10006",
    date: "2026-07-28",
    name: "Uber",
    type: "Expense",
    category: "Transport",
    amount: 315,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Airport ride",
  },
  {
    id: "TXN-10007",
    date: "2026-07-28",
    name: "Netflix",
    type: "Expense",
    category: "Subscription",
    amount: 649,
    paymentMethod: "Debit Card",
    status: "Completed",
    remarks: "Monthly subscription",
  },
  {
    id: "TXN-10008",
    date: "2026-07-27",
    name: "Dividend",
    type: "Income",
    category: "Investment",
    amount: 5400,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Quarterly dividend",
  },
  {
    id: "TXN-10009",
    date: "2026-07-26",
    name: "Apollo Pharmacy",
    type: "Expense",
    category: "Healthcare",
    amount: 980,
    paymentMethod: "UPI",
    status: "Completed",
    remarks: "Medicines",
  },
  {
    id: "TXN-10010",
    date: "2026-07-25",
    name: "Pizza Hut",
    type: "Expense",
    category: "Food & Drinks",
    amount: 1125,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Dinner",
  },
  {
    id: "TXN-10011",
    date: "2026-07-24",
    name: "Google Play",
    type: "Expense",
    category: "Digital",
    amount: 199,
    paymentMethod: "UPI",
    status: "Completed",
    remarks: "Premium app",
  },
  {
    id: "TXN-10012",
    date: "2026-07-23",
    name: "Client Payment",
    type: "Income",
    category: "Business",
    amount: 48000,
    paymentMethod: "Bank Transfer",
    status: "Pending",
    remarks: "Invoice #1024",
  },
  {
    id: "TXN-10013",
    date: "2026-07-22",
    name: "Big Bazaar",
    type: "Expense",
    category: "Groceries",
    amount: 3560,
    paymentMethod: "Debit Card",
    status: "Completed",
    remarks: "Weekly groceries",
  },
  {
    id: "TXN-10014",
    date: "2026-07-21",
    name: "Fuel Station",
    type: "Expense",
    category: "Fuel",
    amount: 2500,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Petrol",
  },
  {
    id: "TXN-10015",
    date: "2026-07-20",
    name: "Interest Credit",
    type: "Income",
    category: "Savings",
    amount: 980,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Savings interest",
  },
  {
    id: "TXN-10004",
    date: "2026-07-30",
    name: "Electricity Bill",
    type: "Expense",
    category: "Utilities",
    amount: 1840,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "July bill",
  },
  {
    id: "TXN-10005",
    date: "2026-07-29",
    name: "Freelance Project",
    type: "Income",
    category: "Freelance",
    amount: 22000,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Landing page design",
  },
  {
    id: "TXN-10006",
    date: "2026-07-28",
    name: "Uber",
    type: "Expense",
    category: "Transport",
    amount: 315,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Airport ride",
  },
  {
    id: "TXN-10007",
    date: "2026-07-28",
    name: "Netflix",
    type: "Expense",
    category: "Subscription",
    amount: 649,
    paymentMethod: "Debit Card",
    status: "Completed",
    remarks: "Monthly subscription",
  },
  {
    id: "TXN-10008",
    date: "2026-07-27",
    name: "Dividend",
    type: "Income",
    category: "Investment",
    amount: 5400,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Quarterly dividend",
  },
  {
    id: "TXN-10009",
    date: "2026-07-26",
    name: "Apollo Pharmacy",
    type: "Expense",
    category: "Healthcare",
    amount: 980,
    paymentMethod: "UPI",
    status: "Completed",
    remarks: "Medicines",
  },
  {
    id: "TXN-10010",
    date: "2026-07-25",
    name: "Pizza Hut",
    type: "Expense",
    category: "Food & Drinks",
    amount: 1125,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Dinner",
  },
  {
    id: "TXN-10011",
    date: "2026-07-24",
    name: "Google Play",
    type: "Expense",
    category: "Digital",
    amount: 199,
    paymentMethod: "UPI",
    status: "Completed",
    remarks: "Premium app",
  },
  {
    id: "TXN-10012",
    date: "2026-07-23",
    name: "Client Payment",
    type: "Income",
    category: "Business",
    amount: 48000,
    paymentMethod: "Bank Transfer",
    status: "Pending",
    remarks: "Invoice #1024",
  },
  {
    id: "TXN-10013",
    date: "2026-07-22",
    name: "Big Bazaar",
    type: "Expense",
    category: "Groceries",
    amount: 3560,
    paymentMethod: "Debit Card",
    status: "Completed",
    remarks: "Weekly groceries",
  },
  {
    id: "TXN-10014",
    date: "2026-07-21",
    name: "Fuel Station",
    type: "Expense",
    category: "Fuel",
    amount: 2500,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Petrol",
  },
  {
    id: "TXN-10015",
    date: "2026-07-20",
    name: "Interest Credit",
    type: "Income",
    category: "Savings",
    amount: 980,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Savings interest",
  },
  {
    id: "TXN-10004",
    date: "2026-07-30",
    name: "Electricity Bill",
    type: "Expense",
    category: "Utilities",
    amount: 1840,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "July bill",
  },
  {
    id: "TXN-10005",
    date: "2026-07-29",
    name: "Freelance Project",
    type: "Income",
    category: "Freelance",
    amount: 22000,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Landing page design",
  },
  {
    id: "TXN-10006",
    date: "2026-07-28",
    name: "Uber",
    type: "Expense",
    category: "Transport",
    amount: 315,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Airport ride",
  },
  {
    id: "TXN-10007",
    date: "2026-07-28",
    name: "Netflix",
    type: "Expense",
    category: "Subscription",
    amount: 649,
    paymentMethod: "Debit Card",
    status: "Completed",
    remarks: "Monthly subscription",
  },
  {
    id: "TXN-10008",
    date: "2026-07-27",
    name: "Dividend",
    type: "Income",
    category: "Investment",
    amount: 5400,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Quarterly dividend",
  },
  {
    id: "TXN-10009",
    date: "2026-07-26",
    name: "Apollo Pharmacy",
    type: "Expense",
    category: "Healthcare",
    amount: 980,
    paymentMethod: "UPI",
    status: "Completed",
    remarks: "Medicines",
  },
  {
    id: "TXN-10010",
    date: "2026-07-25",
    name: "Pizza Hut",
    type: "Expense",
    category: "Food & Drinks",
    amount: 1125,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Dinner",
  },
  {
    id: "TXN-10011",
    date: "2026-07-24",
    name: "Google Play",
    type: "Expense",
    category: "Digital",
    amount: 199,
    paymentMethod: "UPI",
    status: "Completed",
    remarks: "Premium app",
  },
  {
    id: "TXN-10012",
    date: "2026-07-23",
    name: "Client Payment",
    type: "Income",
    category: "Business",
    amount: 48000,
    paymentMethod: "Bank Transfer",
    status: "Pending",
    remarks: "Invoice #1024",
  },
  {
    id: "TXN-10013",
    date: "2026-07-22",
    name: "Big Bazaar",
    type: "Expense",
    category: "Groceries",
    amount: 3560,
    paymentMethod: "Debit Card",
    status: "Completed",
    remarks: "Weekly groceries",
  },
  {
    id: "TXN-10014",
    date: "2026-07-21",
    name: "Fuel Station",
    type: "Expense",
    category: "Fuel",
    amount: 2500,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Petrol",
  },
  {
    id: "TXN-10015",
    date: "2026-07-20",
    name: "Interest Credit",
    type: "Income",
    category: "Savings",
    amount: 980,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Savings interest",
  },
  {
    id: "TXN-10004",
    date: "2026-07-30",
    name: "Electricity Bill",
    type: "Expense",
    category: "Utilities",
    amount: 1840,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "July bill",
  },
  {
    id: "TXN-10005",
    date: "2026-07-29",
    name: "Freelance Project",
    type: "Income",
    category: "Freelance",
    amount: 22000,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Landing page design",
  },
  {
    id: "TXN-10006",
    date: "2026-07-28",
    name: "Uber",
    type: "Expense",
    category: "Transport",
    amount: 315,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Airport ride",
  },
  {
    id: "TXN-10007",
    date: "2026-07-28",
    name: "Netflix",
    type: "Expense",
    category: "Subscription",
    amount: 649,
    paymentMethod: "Debit Card",
    status: "Completed",
    remarks: "Monthly subscription",
  },
  {
    id: "TXN-10008",
    date: "2026-07-27",
    name: "Dividend",
    type: "Income",
    category: "Investment",
    amount: 5400,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Quarterly dividend",
  },
  {
    id: "TXN-10009",
    date: "2026-07-26",
    name: "Apollo Pharmacy",
    type: "Expense",
    category: "Healthcare",
    amount: 980,
    paymentMethod: "UPI",
    status: "Completed",
    remarks: "Medicines",
  },
  {
    id: "TXN-10010",
    date: "2026-07-25",
    name: "Pizza Hut",
    type: "Expense",
    category: "Food & Drinks",
    amount: 1125,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Dinner",
  },
  {
    id: "TXN-10011",
    date: "2026-07-24",
    name: "Google Play",
    type: "Expense",
    category: "Digital",
    amount: 199,
    paymentMethod: "UPI",
    status: "Completed",
    remarks: "Premium app",
  },
  {
    id: "TXN-10012",
    date: "2026-07-23",
    name: "Client Payment",
    type: "Income",
    category: "Business",
    amount: 48000,
    paymentMethod: "Bank Transfer",
    status: "Pending",
    remarks: "Invoice #1024",
  },
  {
    id: "TXN-10013",
    date: "2026-07-22",
    name: "Big Bazaar",
    type: "Expense",
    category: "Groceries",
    amount: 3560,
    paymentMethod: "Debit Card",
    status: "Completed",
    remarks: "Weekly groceries",
  },
  {
    id: "TXN-10014",
    date: "2026-07-21",
    name: "Fuel Station",
    type: "Expense",
    category: "Fuel",
    amount: 2500,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Petrol",
  },
  {
    id: "TXN-10015",
    date: "2026-07-20",
    name: "Interest Credit",
    type: "Income",
    category: "Savings",
    amount: 980,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Savings interest",
  },
  {
    id: "TXN-10004",
    date: "2026-07-30",
    name: "Electricity Bill",
    type: "Expense",
    category: "Utilities",
    amount: 1840,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "July bill",
  },
  {
    id: "TXN-10005",
    date: "2026-07-29",
    name: "Freelance Project",
    type: "Income",
    category: "Freelance",
    amount: 22000,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Landing page design",
  },
  {
    id: "TXN-10006",
    date: "2026-07-28",
    name: "Uber",
    type: "Expense",
    category: "Transport",
    amount: 315,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Airport ride",
  },
  {
    id: "TXN-10007",
    date: "2026-07-28",
    name: "Netflix",
    type: "Expense",
    category: "Subscription",
    amount: 649,
    paymentMethod: "Debit Card",
    status: "Completed",
    remarks: "Monthly subscription",
  },
  {
    id: "TXN-10008",
    date: "2026-07-27",
    name: "Dividend",
    type: "Income",
    category: "Investment",
    amount: 5400,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Quarterly dividend",
  },
  {
    id: "TXN-10009",
    date: "2026-07-26",
    name: "Apollo Pharmacy",
    type: "Expense",
    category: "Healthcare",
    amount: 980,
    paymentMethod: "UPI",
    status: "Completed",
    remarks: "Medicines",
  },
  {
    id: "TXN-10010",
    date: "2026-07-25",
    name: "Pizza Hut",
    type: "Expense",
    category: "Food & Drinks",
    amount: 1125,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Dinner",
  },
  {
    id: "TXN-10011",
    date: "2026-07-24",
    name: "Google Play",
    type: "Expense",
    category: "Digital",
    amount: 199,
    paymentMethod: "UPI",
    status: "Completed",
    remarks: "Premium app",
  },
  {
    id: "TXN-10012",
    date: "2026-07-23",
    name: "Client Payment",
    type: "Income",
    category: "Business",
    amount: 48000,
    paymentMethod: "Bank Transfer",
    status: "Pending",
    remarks: "Invoice #1024",
  },
  {
    id: "TXN-10013",
    date: "2026-07-22",
    name: "Big Bazaar",
    type: "Expense",
    category: "Groceries",
    amount: 3560,
    paymentMethod: "Debit Card",
    status: "Completed",
    remarks: "Weekly groceries",
  },
  {
    id: "TXN-10014",
    date: "2026-07-21",
    name: "Fuel Station",
    type: "Expense",
    category: "Fuel",
    amount: 2500,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Petrol",
  },
  {
    id: "TXN-10015",
    date: "2026-07-20",
    name: "Interest Credit",
    type: "Income",
    category: "Savings",
    amount: 980,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Savings interest",
  },
  {
    id: "TXN-10004",
    date: "2026-07-30",
    name: "Electricity Bill",
    type: "Expense",
    category: "Utilities",
    amount: 1840,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "July bill",
  },
  {
    id: "TXN-10005",
    date: "2026-07-29",
    name: "Freelance Project",
    type: "Income",
    category: "Freelance",
    amount: 22000,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Landing page design",
  },
  {
    id: "TXN-10006",
    date: "2026-07-28",
    name: "Uber",
    type: "Expense",
    category: "Transport",
    amount: 315,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Airport ride",
  },
  {
    id: "TXN-10007",
    date: "2026-07-28",
    name: "Netflix",
    type: "Expense",
    category: "Subscription",
    amount: 649,
    paymentMethod: "Debit Card",
    status: "Completed",
    remarks: "Monthly subscription",
  },
  {
    id: "TXN-10008",
    date: "2026-07-27",
    name: "Dividend",
    type: "Income",
    category: "Investment",
    amount: 5400,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Quarterly dividend",
  },
  {
    id: "TXN-10009",
    date: "2026-07-26",
    name: "Apollo Pharmacy",
    type: "Expense",
    category: "Healthcare",
    amount: 980,
    paymentMethod: "UPI",
    status: "Completed",
    remarks: "Medicines",
  },
  {
    id: "TXN-10010",
    date: "2026-07-25",
    name: "Pizza Hut",
    type: "Expense",
    category: "Food & Drinks",
    amount: 1125,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Dinner",
  },
  {
    id: "TXN-10011",
    date: "2026-07-24",
    name: "Google Play",
    type: "Expense",
    category: "Digital",
    amount: 199,
    paymentMethod: "UPI",
    status: "Completed",
    remarks: "Premium app",
  },
  {
    id: "TXN-10012",
    date: "2026-07-23",
    name: "Client Payment",
    type: "Income",
    category: "Business",
    amount: 48000,
    paymentMethod: "Bank Transfer",
    status: "Pending",
    remarks: "Invoice #1024",
  },
  {
    id: "TXN-10013",
    date: "2026-07-22",
    name: "Big Bazaar",
    type: "Expense",
    category: "Groceries",
    amount: 3560,
    paymentMethod: "Debit Card",
    status: "Completed",
    remarks: "Weekly groceries",
  },
  {
    id: "TXN-10014",
    date: "2026-07-21",
    name: "Fuel Station",
    type: "Expense",
    category: "Fuel",
    amount: 2500,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Petrol",
  },
  {
    id: "TXN-10015",
    date: "2026-07-20",
    name: "Interest Credit",
    type: "Income",
    category: "Savings",
    amount: 980,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Savings interest",
  },
  {
    id: "TXN-10004",
    date: "2026-07-30",
    name: "Electricity Bill",
    type: "Expense",
    category: "Utilities",
    amount: 1840,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "July bill",
  },
  {
    id: "TXN-10005",
    date: "2026-07-29",
    name: "Freelance Project",
    type: "Income",
    category: "Freelance",
    amount: 22000,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Landing page design",
  },
  {
    id: "TXN-10006",
    date: "2026-07-28",
    name: "Uber",
    type: "Expense",
    category: "Transport",
    amount: 315,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Airport ride",
  },
  {
    id: "TXN-10007",
    date: "2026-07-28",
    name: "Netflix",
    type: "Expense",
    category: "Subscription",
    amount: 649,
    paymentMethod: "Debit Card",
    status: "Completed",
    remarks: "Monthly subscription",
  },
  {
    id: "TXN-10008",
    date: "2026-07-27",
    name: "Dividend",
    type: "Income",
    category: "Investment",
    amount: 5400,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Quarterly dividend",
  },
  {
    id: "TXN-10009",
    date: "2026-07-26",
    name: "Apollo Pharmacy",
    type: "Expense",
    category: "Healthcare",
    amount: 980,
    paymentMethod: "UPI",
    status: "Completed",
    remarks: "Medicines",
  },
  {
    id: "TXN-10010",
    date: "2026-07-25",
    name: "Pizza Hut",
    type: "Expense",
    category: "Food & Drinks",
    amount: 1125,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Dinner",
  },
  {
    id: "TXN-10011",
    date: "2026-07-24",
    name: "Google Play",
    type: "Expense",
    category: "Digital",
    amount: 199,
    paymentMethod: "UPI",
    status: "Completed",
    remarks: "Premium app",
  },
  {
    id: "TXN-10012",
    date: "2026-07-23",
    name: "Client Payment",
    type: "Income",
    category: "Business",
    amount: 48000,
    paymentMethod: "Bank Transfer",
    status: "Pending",
    remarks: "Invoice #1024",
  },
  {
    id: "TXN-10013",
    date: "2026-07-22",
    name: "Big Bazaar",
    type: "Expense",
    category: "Groceries",
    amount: 3560,
    paymentMethod: "Debit Card",
    status: "Completed",
    remarks: "Weekly groceries",
  },
  {
    id: "TXN-10014",
    date: "2026-07-21",
    name: "Fuel Station",
    type: "Expense",
    category: "Fuel",
    amount: 2500,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Petrol",
  },
  {
    id: "TXN-10015",
    date: "2026-07-20",
    name: "Interest Credit",
    type: "Income",
    category: "Savings",
    amount: 980,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Savings interest",
  },
  {
    id: "TXN-10004",
    date: "2026-07-30",
    name: "Electricity Bill",
    type: "Expense",
    category: "Utilities",
    amount: 1840,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "July bill",
  },
  {
    id: "TXN-10005",
    date: "2026-07-29",
    name: "Freelance Project",
    type: "Income",
    category: "Freelance",
    amount: 22000,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Landing page design",
  },
  {
    id: "TXN-10006",
    date: "2026-07-28",
    name: "Uber",
    type: "Expense",
    category: "Transport",
    amount: 315,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Airport ride",
  },
  {
    id: "TXN-10007",
    date: "2026-07-28",
    name: "Netflix",
    type: "Expense",
    category: "Subscription",
    amount: 649,
    paymentMethod: "Debit Card",
    status: "Completed",
    remarks: "Monthly subscription",
  },
  {
    id: "TXN-10008",
    date: "2026-07-27",
    name: "Dividend",
    type: "Income",
    category: "Investment",
    amount: 5400,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Quarterly dividend",
  },
  {
    id: "TXN-10009",
    date: "2026-07-26",
    name: "Apollo Pharmacy",
    type: "Expense",
    category: "Healthcare",
    amount: 980,
    paymentMethod: "UPI",
    status: "Completed",
    remarks: "Medicines",
  },
  {
    id: "TXN-10010",
    date: "2026-07-25",
    name: "Pizza Hut",
    type: "Expense",
    category: "Food & Drinks",
    amount: 1125,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Dinner",
  },
  {
    id: "TXN-10011",
    date: "2026-07-24",
    name: "Google Play",
    type: "Expense",
    category: "Digital",
    amount: 199,
    paymentMethod: "UPI",
    status: "Completed",
    remarks: "Premium app",
  },
  {
    id: "TXN-10012",
    date: "2026-07-23",
    name: "Client Payment",
    type: "Income",
    category: "Business",
    amount: 48000,
    paymentMethod: "Bank Transfer",
    status: "Pending",
    remarks: "Invoice #1024",
  },
  {
    id: "TXN-10013",
    date: "2026-07-22",
    name: "Big Bazaar",
    type: "Expense",
    category: "Groceries",
    amount: 3560,
    paymentMethod: "Debit Card",
    status: "Completed",
    remarks: "Weekly groceries",
  },
  {
    id: "TXN-10014",
    date: "2026-07-21",
    name: "Fuel Station",
    type: "Expense",
    category: "Fuel",
    amount: 2500,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Petrol",
  },
  {
    id: "TXN-10015",
    date: "2026-07-20",
    name: "Interest Credit",
    type: "Income",
    category: "Savings",
    amount: 980,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Savings interest",
  },
  {
    id: "TXN-10004",
    date: "2026-07-30",
    name: "Electricity Bill",
    type: "Expense",
    category: "Utilities",
    amount: 1840,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "July bill",
  },
  {
    id: "TXN-10005",
    date: "2026-07-29",
    name: "Freelance Project",
    type: "Income",
    category: "Freelance",
    amount: 22000,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Landing page design",
  },
  {
    id: "TXN-10006",
    date: "2026-07-28",
    name: "Uber",
    type: "Expense",
    category: "Transport",
    amount: 315,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Airport ride",
  },
  {
    id: "TXN-10007",
    date: "2026-07-28",
    name: "Netflix",
    type: "Expense",
    category: "Subscription",
    amount: 649,
    paymentMethod: "Debit Card",
    status: "Completed",
    remarks: "Monthly subscription",
  },
  {
    id: "TXN-10008",
    date: "2026-07-27",
    name: "Dividend",
    type: "Income",
    category: "Investment",
    amount: 5400,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Quarterly dividend",
  },
  {
    id: "TXN-10009",
    date: "2026-07-26",
    name: "Apollo Pharmacy",
    type: "Expense",
    category: "Healthcare",
    amount: 980,
    paymentMethod: "UPI",
    status: "Completed",
    remarks: "Medicines",
  },
  {
    id: "TXN-10010",
    date: "2026-07-25",
    name: "Pizza Hut",
    type: "Expense",
    category: "Food & Drinks",
    amount: 1125,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Dinner",
  },
  {
    id: "TXN-10011",
    date: "2026-07-24",
    name: "Google Play",
    type: "Expense",
    category: "Digital",
    amount: 199,
    paymentMethod: "UPI",
    status: "Completed",
    remarks: "Premium app",
  },
  {
    id: "TXN-10012",
    date: "2026-07-23",
    name: "Client Payment",
    type: "Income",
    category: "Business",
    amount: 48000,
    paymentMethod: "Bank Transfer",
    status: "Pending",
    remarks: "Invoice #1024",
  },
  {
    id: "TXN-10013",
    date: "2026-07-22",
    name: "Big Bazaar",
    type: "Expense",
    category: "Groceries",
    amount: 3560,
    paymentMethod: "Debit Card",
    status: "Completed",
    remarks: "Weekly groceries",
  },
  {
    id: "TXN-10014",
    date: "2026-07-21",
    name: "Fuel Station",
    type: "Expense",
    category: "Fuel",
    amount: 2500,
    paymentMethod: "Credit Card",
    status: "Completed",
    remarks: "Petrol",
  },
  {
    id: "TXN-10015",
    date: "2026-07-20",
    name: "Interest Credit",
    type: "Income",
    category: "Savings",
    amount: 980,
    paymentMethod: "Bank Transfer",
    status: "Completed",
    remarks: "Savings interest",
  },
];

const columns = [
  {
    accessorKey: "date",
    header: "Date",
  },
  {
    accessorKey: "name",
    header: "Name",
  },
  {
    accessorKey: "type",
    header: "Type",
  },
  {
    accessorKey: "category",
    header: "Category",
  },
  {
    accessorKey: "amount",
    header: "Amount",
  },
  {
    accessorKey: "paymentMethod",
    header: "Payment",
  },
  {
    accessorKey: "note",
    header: "Note",
  },
];

export default function Transactions() {
  return (
    <div className="table-contanier">
      <Table
        columns={columns}
        data={transactions}
        pageSize={20}
        rowHeight={42}
        selectable
        sortable
        virtualized
        infiniteScroll
      />
    </div>
  );
}
